## Mapping UMLS vaccine terms to VO

In [1]:
import requests
from typing import List, Sequence, Tuple, Optional, Callable, Union
import pandas as pd
import pickle
from tqdm import tqdm
import concurrent.futures
import time
from threading import Lock
from functools import wraps

Rationale: UMLS has two concepts (CUIs) related to vaccines: 
1. Vaccines (C0042210)
2. Vaccine [APC] (C5399710)

The goal would be to: 
1. Base CUI [X]
2. Get all atoms (AUIs) of the two Vaccine concepts (occurences within source vocabularies) - Limited to english language. This yields 36 AUIs
3. Get descendents for all atoms (AUIs) extracted in previous step
4. For all unique concepts (CUIs) extracted in previous step, extract related atoms
5. For each newly identified CUI, extract relations again (with a depth limit) to find nested vaccine products/formulations

### UMLS API DOC [https://documentation.uts.nlm.nih.gov/rest/home.html]

In [2]:
apikey = '0c4d7175-6688-4c45-9a13-4c64d7354673'
uri = 'https://uts-ws.nlm.nih.gov/rest'

# Get descendants of vaccine concepts:

In [ ]:
# !! get comparison of vocabs in umls vs athena !! 
 # BASIC STATS (vocab,  # concepts)

In [3]:
class RateLimiter:
    def __init__(self, max_calls_per_second=5):
        self.max_calls_per_second = max_calls_per_second
        self.min_interval = 1.0 / max_calls_per_second
        self.last_called = 0
        self.lock = Lock()
    
    def wait(self):
        with self.lock:
            elapsed = time.time() - self.last_called
            left_to_wait = self.min_interval - elapsed
            if left_to_wait > 0:
                time.sleep(left_to_wait)
            self.last_called = time.time()

rate_limiter = RateLimiter(max_calls_per_second=10)

In [4]:
def rate_limited(rate_limiter: RateLimiter):
    def decorator(func):
        @wraps(func)
        def wrapper(*args, **kwargs):
            rate_limiter.wait()
            return func(*args, **kwargs)
        return wrapper
    return decorator

In [5]:
def threaded_umls_fetch(
    cui_list: List[str],
    apikey: str,
    fetch_func: Callable[[str, str], Union[dict, List[dict]]],
    desc: str = "Fetching UMLS data",
    max_workers: int = 10
):
    results = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = {
            executor.submit(fetch_func, cui, apikey): cui
            for cui in cui_list
        }
        with tqdm(total=len(cui_list), desc=desc) as pbar:
            for future in concurrent.futures.as_completed(futures):
                cui = futures[future]
                try:
                    result = future.result()
                    if isinstance(result, list):
                        results.extend(result)
                    else:
                        results.append(result)
                    pbar.set_postfix({"Current CUI": cui})
                except Exception as e:
                    print(f"Error fetching CUI {cui}: {e}")
                pbar.update(1)
    return results

In [ ]:
# Retrieve all atoms for UMLS vaccines (C0042210, C5399710)
#https://documentation.uts.nlm.nih.gov/rest/atoms/
@rate_limited(rate_limiter)
def get_umls_atoms(cui: str, apiKey : str, lang = "ENG", pageNumber = 1 ) -> List[dict]:
    all_atoms = []
    UMLS_ATOM_URL = f'{uri}/content/current/CUI/{{cui}}/atoms'
    while True: 
        response = requests.get(UMLS_ATOM_URL.format(cui=cui), params={'apiKey': apiKey, 'language': lang, 'pageNumber': pageNumber})
        response.encoding = 'utf-8'
        if response.status_code != 200:
            break
        atoms = response.json().get('result', {})
        if not atoms:
            break
        all_atoms.extend(atoms)
        pageNumber += 1
    return all_atoms

In [7]:
# Retrieve all descendants for a given UMLS Atom
# https://documentation.uts.nlm.nih.gov/rest/atoms/ancestors-and-descendants/index.html
@rate_limited(rate_limiter)
def get_umls_descendants(aui: str, apiKey: str, lang: str = "ENG", pageNumber: int = 1) -> List[dict]:
    all_descendants = []
    UMLS_DESCENDANT_URL = f'{uri}/content/current/AUI/{{aui}}/descendants'
    while True:
        response = requests.get(UMLS_DESCENDANT_URL.format(aui=aui), params={'apiKey': apiKey, 'language': lang, 'pageNumber': pageNumber})
        response.encoding = 'utf-8'
        if response.status_code != 200:
            break
        descendants = response.json().get('result', {})
        if not descendants:
            break
        all_descendants.extend(descendants)
        pageNumber += 1
    return all_descendants

In [8]:
# Retrieve all related atoms for a given UMLS concept
# https://documentation.uts.nlm.nih.gov/rest/relations/
@rate_limited(rate_limiter)
def get_related_concepts(cui: str, apiKey: str, relation_types: List[str] = None, pageNumber: int = 1) -> List[dict]:
    all_related = []
    UMLS_RELATION_URL = f'{uri}/content/current/CUI/{{cui}}/relations'
    while True:
        response = requests.get(UMLS_RELATION_URL.format(cui=cui), params={'apiKey': apiKey, 'pageNumber': pageNumber})
        response.encoding = 'utf-8'
        if response.status_code != 200:
            break
        related = response.json().get('result', {})
        if relation_types:
            related = [item for item in related if item.get('relationLabel') in relation_types]
        if not related:
            break
        all_related.extend(related)
        pageNumber += 1
    return all_related

In [9]:
# Retrieve all related atoms for a given atom
#https://documentation.uts.nlm.nih.gov/rest/source-asserted-identifiers/relations/
@rate_limited(rate_limiter)
def get_related_atoms(aui: str, apiKey: str, relations_url:str = None, relation_types: List[str] = None, pageNumber: int = 1) -> List[dict]:
    if not relations_url:
        relations_url = f'{uri}/content/current/AUI/{{aui}}/relations' # needs to be updated with the correct URL
    all_related = []
    while True:
        if relation_types:
            params = {'apiKey': apiKey, 'pageNumber': pageNumber, 'includeRelationLabels': relation_types}
        else:
            params = {'apiKey': apiKey, 'pageNumber': pageNumber}
        response = requests.get(relations_url.format(aui=aui), params=params)
        response.encoding = 'utf-8'
        if response.status_code != 200:
            break
        related = response.json().get('result', {})
        if not related:
            break
        all_related.extend(related)
        pageNumber += 1
    return all_related

In [17]:
# Get umls CUI for atom (https://documentation.uts.nlm.nih.gov/rest/atoms/)
@rate_limited(rate_limiter)
def get_umls_cui(aui: str, apiKey: str, aui_url: str = None) -> Optional[str]:
    if not aui_url:
        aui_url = f'{uri}/content/current/AUI/{{aui}}'
    response = requests.get(aui_url.format(aui=aui), params={'apiKey': apiKey})
    response.encoding = 'utf-8'
    if response.status_code != 200:
        return None
    atom_info = response.json().get('result', {})
    return atom_info.get('concept', None)

In [52]:
# Get rxnorm aui 
@rate_limited(rate_limiter)
def get_rxnorm_aui(rxcui: str, apiKey: str, rxcui_url: str = None) -> Optional[str]:
    if not rxcui_url:
        rxcui_url = f'{uri}/content/current/source/RXNORM/{rxcui}'
    response = requests.get(rxcui_url.format(rxcui=rxcui), params={'apiKey': apiKey})
    response.encoding = 'utf-8'
    if response.status_code != 200:
        return None
    rxcui_info = response.json().get('result', {})
    return rxcui_info.get('ui', None)

#### 1. Vaccine Atoms belonging to 'C0042210', 'C5399710' :

In [10]:
vaccine_cuis = ['C0042210', 'C5399710']
vaccine_atoms = threaded_umls_fetch(vaccine_cuis, apikey, get_umls_atoms, desc="Fetching UMLS Atoms", max_workers=5)

Fetching UMLS Atoms: 100%|██████████| 2/2 [00:00<00:00,  3.08it/s, Current CUI=C0042210]

In [11]:
vac_atom_df = pd.DataFrame(vaccine_atoms)
vac_atom_df

,classType,ui,sourceDescriptor,sourceConcept,concept,suppressible,obsolete,rootSource,termType,code,language,name,ancestors,descendants,attributes,relations,children,parents
0,Atom,A32340275,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,MTH,PN,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,Vaccine [APC],NONE,NONE,NONE,NONE,NONE,NONE
1,Atom,A32340089,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,MED-RT,PT,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,Vaccine,NONE,NONE,NONE,NONE,NONE,NONE
2,Atom,A32340077,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,MED-RT,FN,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,Vaccine [APC],NONE,NONE,NONE,NONE,NONE,NONE
3,Atom,A24665667,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,USPMG,HC,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,Vaccines,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...
4,Atom,A22722839,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,ATC,PT,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,VACCINES,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...
5,Atom,A32282011,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,MSH,ET,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,Vaccine,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,NONE,NONE
6,Atom,A0131113,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,LCH,PT,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,Vaccines,NONE,NONE,NONE,NONE,NONE,NONE
7,Atom,A23870698,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,LCH_NW,PT,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,Vaccines,NONE,NONE,NONE,NONE,NONE,NONE
8,Atom,A1397511,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,AOD,DE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,vaccines,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...
9,Atom,A0806394,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,SNMI,PT,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,"Therapeutic vaccine, NOS",https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...
10,Atom,A19725017,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,HL7V3.0,VS,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,VaccineEntityType,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,NONE,NONE
11,Atom,A12101066,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,VANDF,PT,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,VACCINES,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,NONE
12,Atom,A18618187,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,CHV,PT,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,therapeutic vaccine,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,NONE,NONE
13,Atom,A0806393,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,SNM,PT,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,Therapeutic vaccine,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...
14,Atom,A0815691,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,SNMI,PT,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,"Vaccine, NOS",https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...
15,Atom,A32797963,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,LNC,LPDN,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,Vaccine,NONE,NONE,NONE,NONE,NONE,NONE
16,Atom,A0131115,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,RCD,PT,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,Vaccines,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...
17,Atom,A33486017,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,MEDLINEPLUS,PT,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,Vaccines,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...
18,Atom,A0320232,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,CSP,PT,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,vaccine,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...
19,Atom,A14066811,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,MEDCIN,PT,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,vaccines,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,NONE,NONE
20,Atom,A18581050,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,CHV,SY,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,therapeutic vaccines,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,NONE,NONE
21,Atom,A24099624,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,LNC,LA,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,Vaccines,NONE,NONE,NONE,NONE,NONE,NONE
22,Atom,A7751560,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,MTH,PN,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,Vaccines,NONE,NONE,NONE,NONE,NONE,NONE
23,Atom,A10133377,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,HL7V3.0,PT,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,Vaccine,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...
24,Atom,A18136219,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,LNC,LPN,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,Vaccine,NONE,NONE,NONE,NONE,NONE,NONE
25,Atom,A4367028,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,CSP,ET,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,therapeutic vaccine,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,NONE
26,Atom,A18613338,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,CHV,SY,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,vaccine product,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,NONE,NONE
27,Atom,A18575988,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,CHV,PT,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,vaccine,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,NONE,NONE
28,Atom,A23518358,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,LNC,LS,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,Vaccine,NONE,NONE,NONE,NONE,NONE,NONE
29,Atom,A7589791,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,NCI,PT,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,Vaccine,NONE,NONE,NONE,NONE,NONE,NONE
30,Atom,A13975220,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,MEDCIN,FN,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,vaccines (medication),NONE,NONE,NONE,NONE,NONE,NONE
31,Atom,A0131114,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,MSH,MH,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,Vaccines,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,NONE
32,Atom,A0815124,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,SNMI,HT,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,VACCINES,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...
33,Atom,A18650458,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,CHV,SY,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,vaccines,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,NONE,NONE
34,Atom,A32322129,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,SNOMEDCT_US,FN,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,Vaccine product (medicinal product),NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,NONE,NONE
35,Atom,A31544646,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,SNOMEDCT_US,PT,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,Vaccine product,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,NONE,NONE

#### 2. Descendant Atoms belonging to all Vaccine Atoms :

In [ ]:
# Retrieve all source asserted descendents for all atoms (AUIs) of the two Vaccine concepts
atoms = vac_atom_df['ui'].unique().tolist()
atom_descendants = threaded_umls_fetch(atoms, apikey, get_umls_descendants, desc="Fetching UMLS Descendants", max_workers=5)
print(f"{len(atom_descendants)} source asserted descendants found for {len(atoms)} atoms.")

In [ ]:
atom_descendants_df = pd.DataFrame(atom_descendants)
atom_descendants_df.to_pickle('results/01_atom_descendants.pkl')

In [12]:
atom_descendants_df = pd.read_pickle('results/01_atom_descendants.pkl')
atom_descendants_df

,classType,ui,sourceDescriptor,sourceConcept,concept,suppressible,obsolete,rootSource,termType,code,language,name,ancestors,descendants,attributes,relations,children,parents
0,Atom,A0320257,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,AOD,DE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,viral vaccine,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...
1,Atom,A0318079,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,AOD,DE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,AIDS vaccine,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...
2,Atom,A0474344,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,AOD,DE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,bacterial vaccine,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...
3,Atom,A28934538,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,MED-RT,PT,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,Inactivated Pneumococcal Vaccine,NONE,NONE,NONE,NONE,NONE,NONE
4,Atom,A28934573,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,MED-RT,PT,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,Live Attenuated Rotavirus Vaccine,NONE,NONE,NONE,NONE,NONE,NONE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3313,Atom,A21401058,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,NCI,PT,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,Autologous Pluripotent ALDHbr Stem Cells ALD-451,NONE,NONE,NONE,NONE,NONE,NONE
3314,Atom,A23885829,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,NCI,PT,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,IL-12-expressing Mesenchymal Stem Cell Vaccine...,NONE,NONE,NONE,NONE,NONE,NONE
3315,Atom,A29762108,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,NCI,PT,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,Tonogenchoncel-L,NONE,NONE,NONE,NONE,NONE,NONE
3316,Atom,A32403905,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,NCI,PT,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,Allogeneic Glial Progenitor Cells,NONE,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,NONE
3317,Atom,A32412425,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,NCI,PT,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,Romyelocel-L,NONE,NONE,NONE,NONE,NONE,NONE

#### 3. Atoms related to vaccine atoms:

In [ ]:
# Retrieve all broader concepts (similar to children concepts) for all atoms (AUIs) of the two Vaccine concepts - This provides atoms outside of source vocabularies
# get all values from 'relation' column that is not NONE
atom_rela = vac_atom_df['relations'].unique().tolist()
atom_rela = [item for item in atom_rela if item != 'NONE']
atoms_relations = []
# NEED TO extract just the atoms from the relations. 
for atom_rel in atom_rela: 
    atoms_relations.extend(get_related_atoms(atom_rel, apikey, atom_rel, ["RB", "RO", "RQ", "SY", "RL"]))

In [ ]:
related_df = pd.DataFrame(atoms_relations)
# remove records where column 'additionalRelationLabel' is 'has_translation'
related_df = related_df[related_df['additionalRelationLabel'] != 'has_translation']

In [14]:
related_df['codeClean'] = related_df['relatedId'].apply(lambda x: x.split('/')[-1] if isinstance(x, str) else x)

In [16]:
#Major ToDo: Iterate through descendants key till there is NONE [p2]

In [20]:
# Get source concept (https://documentation.uts.nlm.nih.gov/rest/atoms/)
related_df['sourceCUI'] = related_df.apply(lambda x: get_umls_cui(x['ui'], apikey, x['relatedId']), axis=1)

In [21]:
related_df

,ui,sourceUi,obsolete,suppressible,sourceOriginated,rootSource,relationLabel,additionalRelationLabel,groupId,relatedId,relatedIdName,relatedFromId,relatedFromIdName,attributeCount,classType,codeClean,sourceCUI
0,R00690846,NONE,False,False,False,AOD,RB,,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,viral vaccine,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,vaccines,0,AtomRelation,A0320257,https://uts-ws.nlm.nih.gov/rest/content/2025AA...
1,R00691155,NONE,False,False,False,AOD,RB,,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,bacterial vaccine,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,vaccines,0,AtomRelation,A0474344,https://uts-ws.nlm.nih.gov/rest/content/2025AA...
2,R123774609,NONE,False,False,False,VANDF,RB,inverse_isa,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,MENINGOCOCCAL OLIGOSACCHARIDE CONJUGATE VACCIN...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,VACCINES,0,AtomRelation,A18803744,https://uts-ws.nlm.nih.gov/rest/content/2025AA...
3,R211439176,NONE,False,False,False,VANDF,RB,inverse_isa,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,MENINGOCOCCAL OLIGOSACCHAR CONJ VACCINE (MENVE...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,VACCINES,0,AtomRelation,A34967388,https://uts-ws.nlm.nih.gov/rest/content/2025AA...
4,R70583324,NONE,False,False,False,VANDF,RB,inverse_isa,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,HEPATITIS A 720 EL.U/HEPATITIS B 20MCG/ML VACC...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,VACCINES,0,AtomRelation,A8451724,https://uts-ws.nlm.nih.gov/rest/content/2025AA...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262,R148149150,NONE,False,False,False,MSH,RB,mapped_from,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,SNC-rCTB vaccine,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,Vaccines,0,AtomClusterRelation,C583182,None
263,R148181673,NONE,False,False,False,MSH,RB,mapped_from,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,TA-NIC,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,Vaccines,0,AtomClusterRelation,C582229,None
264,R148235829,NONE,False,False,False,MSH,RB,mapped_from,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NicVAX,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,Vaccines,0,AtomClusterRelation,C557119,None
265,R148154736,NONE,False,False,False,MSH,RB,mapped_from,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,Sj22.6-26GST vaccine,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,Vaccines,0,AtomClusterRelation,C573432,None
266,R18399746,NONE,False,False,False,SNMI,SY,,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,B6 VACCINES,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,VACCINES,0,AtomRelation,A1405572,https://uts-ws.nlm.nih.gov/rest/content/2025AA...

In [22]:
related_df.to_pickle('results/02_related_df.pkl')

In [23]:
related_df = pd.read_pickle('results/02_related_df.pkl')
related_df

,ui,sourceUi,obsolete,suppressible,sourceOriginated,rootSource,relationLabel,additionalRelationLabel,groupId,relatedId,relatedIdName,relatedFromId,relatedFromIdName,attributeCount,classType,codeClean,sourceCUI
0,R00690846,NONE,False,False,False,AOD,RB,,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,viral vaccine,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,vaccines,0,AtomRelation,A0320257,https://uts-ws.nlm.nih.gov/rest/content/2025AA...
1,R00691155,NONE,False,False,False,AOD,RB,,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,bacterial vaccine,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,vaccines,0,AtomRelation,A0474344,https://uts-ws.nlm.nih.gov/rest/content/2025AA...
2,R123774609,NONE,False,False,False,VANDF,RB,inverse_isa,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,MENINGOCOCCAL OLIGOSACCHARIDE CONJUGATE VACCIN...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,VACCINES,0,AtomRelation,A18803744,https://uts-ws.nlm.nih.gov/rest/content/2025AA...
3,R211439176,NONE,False,False,False,VANDF,RB,inverse_isa,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,MENINGOCOCCAL OLIGOSACCHAR CONJ VACCINE (MENVE...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,VACCINES,0,AtomRelation,A34967388,https://uts-ws.nlm.nih.gov/rest/content/2025AA...
4,R70583324,NONE,False,False,False,VANDF,RB,inverse_isa,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,HEPATITIS A 720 EL.U/HEPATITIS B 20MCG/ML VACC...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,VACCINES,0,AtomRelation,A8451724,https://uts-ws.nlm.nih.gov/rest/content/2025AA...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262,R148149150,NONE,False,False,False,MSH,RB,mapped_from,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,SNC-rCTB vaccine,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,Vaccines,0,AtomClusterRelation,C583182,None
263,R148181673,NONE,False,False,False,MSH,RB,mapped_from,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,TA-NIC,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,Vaccines,0,AtomClusterRelation,C582229,None
264,R148235829,NONE,False,False,False,MSH,RB,mapped_from,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NicVAX,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,Vaccines,0,AtomClusterRelation,C557119,None
265,R148154736,NONE,False,False,False,MSH,RB,mapped_from,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,Sj22.6-26GST vaccine,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,Vaccines,0,AtomClusterRelation,C573432,None
266,R18399746,NONE,False,False,False,SNMI,SY,,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,B6 VACCINES,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,VACCINES,0,AtomRelation,A1405572,https://uts-ws.nlm.nih.gov/rest/content/2025AA...

#### 3.5. All atoms of concepts found so far

In [29]:
related_df_cui_list = related_df['sourceCUI'].apply(lambda x: x.split('/')[-1] if isinstance(x, str) else x).dropna().unique().tolist()
atoms_of_related_df_cui_list = threaded_umls_fetch(related_df_cui_list, apikey, get_umls_atoms, desc="Fetching Atoms of Related CUI List", max_workers=5)

Fetching Atoms of Related CUI List: 100%|██████████| 205/205 [00:22<00:00,  9.11it/s, Current CUI=C0042213]

In [33]:
related_atom_df = pd.DataFrame(atoms_of_related_df_cui_list)
related_atom_df.to_pickle('results/03_related_atom_df.pkl')

In [34]:
related_atom_df = pd.read_pickle('results/03_related_atom_df.pkl')
related_atom_df

,classType,ui,sourceDescriptor,sourceConcept,concept,suppressible,obsolete,rootSource,termType,code,language,name,ancestors,descendants,attributes,relations,children,parents
0,Atom,A0132653,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,MTH,PN,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,Viral Vaccines,NONE,NONE,NONE,NONE,NONE,NONE
1,Atom,A18576064,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,CHV,SY,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,viral vaccine,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,NONE,NONE
2,Atom,A0320258,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,CSP,PT,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,viral vaccine,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...
3,Atom,A0470799,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,LCH,PT,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,Viral vaccines,NONE,NONE,NONE,NONE,NONE,NONE
4,Atom,A15199010,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,MEDCIN,FN,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,viral vaccines (medication),NONE,NONE,NONE,NONE,NONE,NONE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1713,Atom,A32284447,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,MSH,PM,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,"Vaccine, Synthetic",NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,NONE
1714,Atom,A26604469,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,MSH,ET,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,Synthetic Immunogens,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,NONE
1715,Atom,A0131129,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,MSH,MH,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,"Vaccines, Synthetic",NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,NONE
1716,Atom,A26644974,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,MSH,ET,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,Synthetic Vaccines,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,NONE
1717,Atom,A26626063,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,MSH,ET,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,"Immunogens, Synthetic",NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,NONE

In [35]:
# Check the total unique atoms
vac_atom_df_atoms = vac_atom_df['ui'].unique().tolist()
atom_descendants_df_atoms = atom_descendants_df['ui'].unique().tolist()
related_atom_df_atoms = related_atom_df['ui'].unique().tolist()
atom_list = vac_atom_df_atoms + atom_descendants_df_atoms + related_atom_df_atoms
total_unique_atoms = set()
for atom in atom_list:
    if isinstance(atom, str):
        total_unique_atoms.add(atom)
len(total_unique_atoms)

4242

#### 3.5.1 Bandage for Rxnorm:

In [50]:
rxnav_df = pd.read_pickle("rxnav_data.pkl")
rxnav_df

        rxcui                                              label  status   tty
0     2566422  0.5 ML Streptococcus pneumoniae serotype 1 cap...  Active   SBD
1     2687724                                  Fluzone 2024-2025  Active    BN
2     1601400  Neisseria meningitidis serogroup B strain NZ98...  Active  SCDC
3     2270606  Vibrio cholerae CVD 103-HGR strain live antige...  Active  SCDG
4     1190919  0.5 ML diphtheria toxoid vaccine, inactivated ...  Active   SBD
...       ...                                                ...     ...   ...
1879  2688113  influenza A virus A/Sydney/1304/2022 (H3N2) an...  Active   PIN
1880  2685010                         Mresvia Injectable Product  Active  SBDG
1881  2270605  Vibrio cholerae CVD 103-HGR strain live antige...  Active  SCDG
1882   798231  Streptococcus pneumoniae serotype 6B capsular ...  Active  SCDC
1883  1657429  acellular pertussis vaccine, inactivated / dip...  Active  SCDF

[1884 rows x 4 columns]

In [54]:
rxcui_list = rxnav_df['rxcui'].dropna().unique().tolist()
rxcui_auis = threaded_umls_fetch(rxcui_list, apikey, get_rxnorm_aui, desc="Fetching RxNorm AUIs", max_workers=15)

Fetching RxNorm AUIs:   0%|          | 0/1884 [00:00<?, ?it/s]

Fetching RxNorm AUIs: 100%|██████████| 1884/1884 [04:11<00:00,  7.48it/s, Current CUI=1657429]

In [64]:
rxcui_auis

['2566422',
 '2687724',
 '1601400',
 '2270606',
 '1190919',
 '1597086',
 '2566408',
 '2642140',
 '1300369',
 '2694019',
 '2593120',
 '1657137',
 '2583643',
 '2280749',
 '2561244',
 '2588240',
 '2603506',
 '2170518',
 '2197292',
 '2109619',
 '2566419',
 '2648742',
 '2664840',
 '2660432',
 '2642409',
 '2645589',
 '798298',
 '1160325',
 '2642408',
 '1994348',
 '1300190',
 '2661479',
 '2270607',
 '2645752',
 '901632',
 '2642412',
 '2649176',
 '1666421',
 '94317',
 '901643',
 None,
 '2648898',
 '2566301',
 '2583644',
 '2641851',
 '798276',
 '2050419',
 '1300307',
 '1653483',
 '2691207',
 '798226',
 '901641',
 '1292441',
 '2605553',
 '854938',
 '845527',
 '1657222',
 '2661458',
 '2677448',
 '2606078',
 '2646500',
 '2664742',
 '830549',
 '2686922',
 '2468230',
 '2685003',
 '2360576',
 '2648632',
 '2603832',
 '854951',
 '1658035',
 '1300384',
 '2636592',
 '2109617',
 '2664827',
 '2624749',
 '2687362',
 '2646219',
 '830261',
 '1597083',
 '798222',
 '901506',
 '2642311',
 None,
 '2658504',
 '2624743',
 '1006915',
 '2605089',
 '901510',
 '2705457',
 '798430',
 '1664471',
 '1153661',
 '798279',
 '2663285',
 '1986822',
 '1653578',
 '2280293',
 '2659680',
 '2661292',
 '2688106',
 '2664801',
 '798438',
 '2691212',
 '2647676',
 '2686968',
 '1657226',
 '1597103',
 '2670562',
 None,
 '1159372',
 '2686952',
 '2686975',
 '2705463',
 '2605039',
 '2606077',
 '807272',
 '2647500',
 '854954',
 '2660964',
 '2694012',
 '2687738',
 '854930',
 '2360580',
 '1099939',
 '2691203',
 '2109613',
 '830245',
 '2659297',
 '1653484',
 '1190911',
 '854941',
 '830550',
 '1657603',
 '1994352',
 '2056521',
 '2566410',
 '829989',
 '2687729',
 '2642202',
 '2694017',
 '2605095',
 '2687722',
 '2663643',
 '2566300',
 '854931',
 '2655522',
 '2687720',
 '2583645',
 '2270604',
 '854972',
 '2624752',
 '830554',
 '2275271',
 '832679',
 '798223',
 '2623376',
 '1007640',
 '2470233',
 '1169156',
 '801709',
 '2646081',
 '1657128',
 '854943',
 '2641878',
 '1300182',
 None,
 '798449',
 '2687360',
 '798365',
 '2645364',
 '854962',
 '1659733',
 '1300779',
 '2566295',
 '2687732',
 '2360571',
 '2605090',
 '2661585',
 '1300185',
 '833083',
 '2273313',
 '2688115',
 '854959',
 '2645581',
 '2654469',
 '1601401',
 '2605566',
 '2649027',
 '2649058',
 '2623382',
 '1658469',
 '2464824',
 '2641826',
 '1300370',
 '2662559',
 '1162391',
 '2646313',
 '2380838',
 '2379531',
 '2588239',
 '2636596',
 '1658149',
 '2654629',
 '2601550',
 '1437910',
 '806594',
 '2641625',
 '2588230',
 '2605538',
 '2664822',
 '2593865',
 '2660938',
 '2655929',
 '2649496',
 '1596930',
 '805577',
 '2645691',
 '2605106',
 '2479834',
 '2050418',
 '2673245',
 '2691301',
 '2636590',
 '2647414',
 '2673239',
 None,
 '2661018',
 '2380835',
 '797632',
 '1300807',
 '1179553',
 '2686959',
 '1153476',
 '114883',
 None,
 None,
 '2197291',
 '2686942',
 '2649329',
 '1547580',
 '2691199',
 '2197699',
 '803371',
 '1300186',
 '798220',
 '2109615',
 '2659304',
 '901515',
 '2673241',
 '2686931',
 '2691179',
 '901622',
 '1657601',
 '2664825',
 '2646137',
 '2593843',
 '2649057',
 '2688132',
 '798447',
 '1928290',
 '2663346',
 '2694005',
 '1657331',
 '1597096',
 '798289',
 '2585714',
 '1008933',
 '854936',
 '1593130',
 '2663157',
 '2583640',
 '2661097',
 '2380575',
 '797638',
 '845525',
 '763097',
 '2177690',
 '2642138',
 '2605724',
 '1292443',
 '606051',
 '798232',
 '1657446',
 '2686934',
 '2627822',
 '2464829',
 '2705465',
 '1657731',
 '797752',
 '2691304',
 '2658688',
 '2656805',
 '832682',
 '763103',
 '1658066',
 None,
 '2562555',
 '2675577',
 '2383544',
 '2607744',
 '1601406',
 '798482',
 '2646393',
 '2624744',
 '2642411',
 '1292826',
 '2686976',
 '2662075',
 '573593',
 '2686924',
 '2677167',
 '1596932',
 '2649098',
 '2642146',
 '2645546',
 '1368371',
 '1986830',
 '2588219',
 '1928289',
 '2660792',
 None,
 '1658143',
 '2623381',
 '1292427',
 '807239',
 '2705466',
 '2664816',
 '2659554',
 '2688135',
 '803370',
 '2688110',
 '2663223',
 '2593118',
 '2642406',
 '1153474',
 '1153475',
 '2605552',
 '2630221',
 '2262062',
 '1167200',
 '2566308',
 '1300364',
 '1176753',
 '2645085',
 '854975',
 '2106332',
 '2687359',
 '2664831',
 '2664726',
 '798304',
 '833082',
 '2641634',
 '1658100',
 '2661013',
 '1593127',
 '807219',
 '2648517',
 '797633',
 '2056523',
 '2607735',
 '2050420',
 '2686929',
 '1994349',
 '2694021',
 '1876706',
 '2705456',
 '2641640',
 '2648842',
 '805378',
 '2666309',
 '2605096',
 '2685004',
 '2177695',
 '2624746',
 '2663544',
 '798300',
 '2605739',
 '2583637',
 '2648686',
 '2658102',
 None,
 None,
 '2636599',
 '1008034',
 '2177692',
 '2687733',
 '2642199',
 None,
 '2587056',
 '2686940',
 '2687721',
 '2605543',
 '2109612',
 '2691195',
 '2686920',
 '798306',
 '1292440',
 '493191',
 '2661143',
 '2664745',
 '2197693',
 '2657585',
 '2273311',
 '2624751',
 '1986828',
 '1876704',
 '798287',
 '2641629',
 '2648207',
 None,
 '2691170',
 '2660869',
 '1151122',
 '2360584',
 '2673240',
 '2647087',
 '2641637',
 '2380836',
 '1657130',
 '1184336',
 '1657878',
 '1986829',
 '2648703',
 '2647696',
 '2641827',
 '1601403',
 '1656973',
 '2275275',
 '2646865',
 '2605103',
 '1653579',
 '762602',
 '1601404',
 '804184',
 '1292423',
 '2054177',
 '1292439',
 '1179526',
 '1300365',
 '1184551',
 '2686948',
 '2566294',
 '2691175',
 '2664832',
 '2641636',
 '1486495',
 '2566303',
 '798288',
 '830243',
 '1190916',
 '2605563',
 '2641877',
 '1186641',
 '1804259',
 '2641825',
 '2660530',
 None,
 '2665609',
 '2694014',
 '854977',
 '2686919',
 '2661883',
 None,
 '2654366',
 '2649290',
 None,
 '2687727',
 '830237',
 '2687737',
 '1008299',
 '2642308',
 '2605569',
 '798307',
 '1601398',
 '2649256',
 '2642299',
 '1657229',
 '2605100',
 '2658262',
 '901629',
 None,
 '1657463',
 '2654461',
 '2649193',
 '2685009',
 '2687734',
 '1300468',
 None,
 '219579',
 '2605092',
 '854957',
 '2601549',
 None,
 None,
 '1986823',
 '2686949',
 '2665606',
 '2646801',
 '1300382',
 '2605728',
 '2688054',
 '901625',
 '2648156',
 '1007545',
 '901634',
 None,
 '901630',
 '1986824',
 '1300389',
 '1946983',
 '2686918',
 '2692306',
 '797645',
 '763100',
 '2050059',
 '804188',
 '901636',
 '316949',
 '1658157',
 '2666310',
 '854932',
 '1994351',
 '2649396',
 '2641887',
 '1653485',
 '830555',
 '2688120',
 '797630',
 '798264',
 '2050422',
 '2691211',
 '763106',
 '1160350',
 '674453',
 '2675676',
 '1593140',
 '2705460',
 '2177691',
 '2659361',
 '2566310',
 '1008495',
 '854945',
 '798224',
 '2659305',
 '1657669',
 '2648451',
 '153189',
 '1300780',
 '2646107',
 '2641628',
 None,
 '2360577',
 '1801767',
 '2662595',
 '2605540',
 '1300180',
 '2607746',
 None,
 '2605737',
 '1155021',
 '2605045',
 '2659787',
 None,
 '2106330',
 '798265',
 '807277',
 '1658029',
 '2566299',
 '2641880',
 '683648',
 '901631',
 '1658102',
 '2282758',
 '1597094',
 '2656812',
 '2603514',
 '2641885',
 '2605726',
 '2636595',
 '2663431',
 '2605536',
 '659877',
 '2605564',
 '2658011',
 '2691308',
 '854942',
 '1658106',
 '2641632',
 '2649382',
 None,
 '2660462',
 '798275',
 '2691176',
 '2660893',
 '218128',
 '2645751',
 '2566406',
 '2670550',
 '1159371',
 '854953',
 '2686963',
 '2661498',
 '2642415',
 '2688052',
 '2636598',
 '2691215',
 '1597095',
 '1300191',
 '2606075',
 '2583650',
 '1658238',
 '2686917',
 '2273310',
 '1184384',
 '1151137',
 '2688050',
 '1300386',
 '2691172',
 '2686928',
 '1601397',
 '2275272',
 '2197701',
 '2360574',
 '1607804',
 '2648158',
 '2686166',
 '2675672',
 '2688108',
 '2686950',
 '901642',
 '798425',
 '2694016',
 '2642314',
 '1169861',
 '1876709',
 '2642315',
 '2642355',
 '2659890',
 '2641828',
 '2605049',
 '2655246',
 '2603507',
 '854960',
 '1659745',
 '2685012',
 '1159373',
 '2675572',
 '2109609',
 '2659647',
 '583411',
 '2660657',
 '1300381',
 '203439',
 '854934',
 '1187407',
 '2641824',
 '2275276',
 '2642309',
 '2275284',
 '797635',
 '2662539',
 '2664830',
 '2656909',
 '2645609',
 '797643',
 '2659136',
 '830253',
 '2686972',
 '2593857',
 '1182565',
 '1658071',
 '2646667',
 '2691298',
 '2645315',
 '2170515',
 '2687735',
 '798476',
 '1099938',
 None,
 '2686960',
 '2603512',
 '721656',
 '727782',
 '1812946',
 '2686953',
 '2610327',
 '2662819',
 '2662653',
 '2691303',
 '2685011',
 '1151123',
 '801712',
 '2688129',
 '1007259',
 '1159739',
 '2691305',
 '798302',
 '854948',
 '1664472',
 '2605561',
 '2663143',
 None,
 '2685006',
 '2605093',
 '1292422',
 '2627824',
 '2647501',
 '1157534',
 '2607750',
 '2566413',
 '1007290',
 '854935',
 '2664828',
 '2642405',
 '2605725',
 '1799447',
 '2686921',
 '1300310',
 '2687741',
 '2593847',
 '2647915',
 '2607742',
 '1161568',
 '2641631',
 '235600',
 '2656498',
 None,
 '1658065',
 '2664841',
 '2646661',
 '1184583',
 '804183',
 '1942125',
 '2686937',
 '2656924',
 '1300309',
 '1593139',
 '2607743',
 '2648837',
 '2645648',
 '2648283',
 '2673247',
 '798267',
 '798299',
 '762597',
 '1812951',
 '352572',
 '798427',
 '1597085',
 '798233',
 '1658057',
 '2688122',
 '854946',
 '2675675',
 '2583646',
 '2464826',
 '797642',
 '1007584',
 '2659296',
 '2670561',
 '2670557',
 '2687739',
 '2687364',
 '2660984',
 '1182566',
 '2642298',
 '2563011',
 '805375',
 '1601399',
 '2603501',
 '2479040',
 '2664725',
 '2566421',
 '2686964',
 '1596933',
 '2647560',
 '2593856',
 '2646988',
 '2686923',
 '798361',
 '2675579',
 '2585717',
 '2566415',
 '2665608',
 '2647202',
 '2648299',
 '1876705',
 '798296',
 '1657871',
 '806586',
 '2645935',
 '2464827',
 '1946964',
 '2605551',
 '1008272',
 '2588237',
 '1597099',
 '1161536',
 '1664473',
 '1657397',
 '2686965',
 '2468236',
 '2691302',
 '2685005',
 '2687740',
 '2050057',
 '1166526',
 '1663632',
 '2642196',
 '2642305',
 '2624745',
 '2642306',
 '1300377',
 '807225',
 '2648241',
 '2661122',
 '854964',
 '2606076',
 '830457',
 '2360583',
 '2645994',
 '2691198',
 '1158641',
 None,
 '2648743',
 '1597093',
 '2050423',
 '2658689',
 '798297',
 '1601231',
 '2272203',
 '1171400',
 '2562553',
 '2641884',
 '2642313',
 '901516',
 '1151133',
 '798277',
 '2647044',
 '2627825',
 '2610326',
 '2686926',
 None,
 '1988804',
 '854961',
 '2655795',
 '1008748',
 '2660583',
 '2056525',
 '854971',
 '798426',
 '797639',
 '2691306',
 '830263',
 '2566409',
 '2645542',
 '605718',
 '1659730',
 '2686974',
 '1161748',
 '798263',
 '2603504',
 '2656067',
 '901505',
 '803362',
 '2688056',
 '2646013',
 '2662734',
 '2607745',
 '2605735',
 '2621900',
 '2655705',
 None,
 '1160324',
 '1649574',
 '2688626',
 '213744',
 '2649336',
 '2603508',
 '2687714',
 None,
 '854949',
 '1177656',
 '2655633',
 '2659708',
 '2280296',
 '854952',
 '2605733',
 '1008344',
 '2686936',
 '1157896',
 '2666311',
 '1986825',
 '797641',
 '2688136',
 '2623377',
 '404894',
 '836636',
 '830556',
 '1099941',
 '1869637',
 '2593854',
 '2050058',
 '1597091',
 '1486496',
 '1657683',
 '2479830',
 '2468237',
 '829987',
 '29501',
 '2645723',
 '1099935',
 '2566304',
 '1488651',
 '2675578',
 '2566314',
 '2662087',
 '804181',
 '2610328',
 '2661062',
 '2642410',
 '2605570',
 '2691218',
 '1658105',
 '2605104',
 '2109616',
 '1657592',
 '2648878',
 '1597102',
 '1292457',
 '2691194',
 '804179',
 '2686925',
 '2705455',
 '2593855',
 '2603503',
 '1657998',
 '1547582',
 '1653577',
 '2655794',
 '1151131',
 '2566298',
 '830470',
 '2605048',
 '1657131',
 '1986826',
 '287523',
 '2627823',
 '2646568',
 '1601405',
 '1166419',
 '1657466',
 '2197300',
 '901511',
 '2686966',
 '2685002',
 '1153958',
 '2050417',
 '2659610',
 '2656180',
 '1657767',
 '1597089',
 '1153961',
 '2645662',
 '1876710',
 '2470232',
 '1300378',
 '1658470',
 '2661370',
 '2583743',
 '845531',
 '1292430',
 '2687728',
 '2587054',
 '1292827',
 '805576',
 '798278',
 '805579',
 '2688114',
 '1099934',
 '2659681',
 '2656341',
 '126542',
 '1593128',
 None,
 None,
 '2623378',
 '1300181',
 '49610',
 '2654370',
 '805376',
 '2197703',
 '2694013',
 '901621',
 '1664171',
 '2360588',
 '798481',
 '1300184',
 '798444',
 ...]

In [59]:
rxnorm_cui = threaded_umls_fetch(rxcui_auis, apikey, get_umls_cui, desc="Fetching RxNorm CUI", max_workers=15)

Fetching RxNorm CUI: 100%|██████████| 1884/1884 [03:08<00:00,  9.99it/s, Current CUI=1657429]

In [62]:
rxnorm_cui_df = pd.DataFrame(rxnorm_cui)
rxnorm_cui_df

         0
0     None
1     None
2     None
3     None
4     None
...    ...
1879  None
1880  None
1881  None
1882  None
1883  None

[1884 rows x 1 columns]

In [38]:
concatonated_df = pd.concat([vac_atom_df, atom_descendants_df, related_atom_df], ignore_index=True)
concatonated_df

,classType,ui,sourceDescriptor,sourceConcept,concept,suppressible,obsolete,rootSource,termType,code,language,name,ancestors,descendants,attributes,relations,children,parents
0,Atom,A32340275,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,MTH,PN,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,Vaccine [APC],NONE,NONE,NONE,NONE,NONE,NONE
1,Atom,A32340089,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,MED-RT,PT,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,Vaccine,NONE,NONE,NONE,NONE,NONE,NONE
2,Atom,A32340077,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,MED-RT,FN,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,Vaccine [APC],NONE,NONE,NONE,NONE,NONE,NONE
3,Atom,A24665667,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,USPMG,HC,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,Vaccines,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...
4,Atom,A22722839,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,ATC,PT,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,VACCINES,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5067,Atom,A32284447,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,MSH,PM,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,"Vaccine, Synthetic",NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,NONE
5068,Atom,A26604469,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,MSH,ET,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,Synthetic Immunogens,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,NONE
5069,Atom,A0131129,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,MSH,MH,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,"Vaccines, Synthetic",NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,NONE
5070,Atom,A26644974,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,MSH,ET,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,Synthetic Vaccines,NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,NONE
5071,Atom,A26626063,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,false,false,MSH,ET,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,ENG,"Immunogens, Synthetic",NONE,NONE,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,https://uts-ws.nlm.nih.gov/rest/content/2025AA...,NONE,NONE

In [40]:
concatonated_df['rootSource'].value_counts()

rootSource
NCI              1531
MEDCIN            684
SNOMEDCT_US       532
RCD               348
RXNORM            304
MSH               294
NDDF              223
VANDF             152
ATC               135
CHV                81
CSP                73
SNMI               71
CVX                56
MTH                54
MMX                48
MMSL               47
GS                 39
USPMG              35
MEDLINEPLUS        33
MED-RT             32
MDR                32
LNC                25
MTHSPL             24
AOD                21
ICPC2ICD10ENG      20
SNM                19
ICPC2P             17
PDQ                14
LCH_NW             14
LCH                11
PSY                 9
ICD10CM             8
CST                 7
DXP                 7
HL7V3.0             6
COSTAR              6
CCS                 6
ICD10               5
BI                  5
NANDA-I             5
ICD10AM             5
CCPSS               4
OMIM                4
CCSR_ICD10CM        3
MTHICD9             3
RCDAE               3
ICD9CM              2
ICPC                2
ICPC2EENG           2
WHO                 2
ICNP                2
QMR                 1
ORPHANET            1
GO                  1
CDT                 1
CCSR_ICD10PCS       1
HL7V2.5             1
CPM                 1
Name: count, dtype: int64

#### 4. Related Atoms belonging to all vaccine descendant atoms:

In [ ]:
#load umls_vaccine_descendants into a pandas dataframe
vac_df = pd.DataFrame(atom_descendants)
vac_df.head()
vac_df.to_pickle('results/umls_vaccine_descendants.pkl')

In [ ]:
vac_df = pd.read_pickle('results/umls_vaccine_descendants.pkl')

In [ ]:
# new column: codeClean where all string after the last '/' is extracted from the code column
vac_df['codeClean'] = vac_df['code'].apply(lambda x: x.split('/')[-1] if isinstance(x, str) else x)
vac_df['conceptClean'] = vac_df['concept'].apply(lambda x: x.split('/')[-1] if isinstance(x, str) else x)
# ToDo: There are some concepts which may not be appropriate (sematic types: Findings, Therapeutic or Preventive Procedure, Health Care Activity etc.) May need to remove them
vac_df

In [ ]:
atoms = vac_df['ui'].unique().tolist()
print(f"Total unique atoms: {len(atoms)}")
related_concepts = threaded_umls_fetch(atoms, apikey, get_umls_descendants, desc="Fetching UMLS Descendants", max_workers=5)

In [ ]:
len(related_concepts)

In [ ]:
related_df = pd.DataFrame(related_concepts)
related_df

In [ ]:
related_df['codeClean'] = related_df['relatedId'].apply(lambda x: x.split('/')[-1] if isinstance(x, str) else x)

In [ ]:
related_df[related_df['codeClean'] == 'A36802459']

#### Test Case: Missing Concept A36802459 - C5941869
> 0.3 ML SARS-CoV-2 (COVID-19) vaccine, mRNA-BNT162b2 OMICRON (KP.2) 0.1 MG/ML Prefilled Syringe [Comirnaty 2024-2025]

In [ ]:
# check if 'A36802459' is in 'ui' column 
vac_df[vac_df['ui'] == 'A36802459']

### Workaround: Try to explode concept column to get atoms again.

In [ ]:
cui_list = vac_df['conceptClean'].unique().tolist()

In [ ]:
len(cui_list)

In [ ]:
exploded_atoms = get_all_atoms_threaded(cui_list, apikey, max_workers=10)

In [ ]:
len(exploded_atoms)

In [ ]:
exploded_df = pd.DataFrame(exploded_atoms)
exploded_df.head()
exploded_df.to_pickle('results/umls_exploded_atoms.pkl')

In [ ]:
exploded_df = pd.read_pickle('results/umls_exploded_atoms.pkl')

In [ ]:
exploded_df['codeClean'] = exploded_df['code'].apply(lambda x: x.split('/')[-1] if isinstance(x, str) else x)
exploded_df['conceptClean'] = exploded_df['concept'].apply(lambda x: x.split('/')[-1] if isinstance(x, str) else x)
exploded_df

In [ ]:
exploded_df['rootSource'].value_counts()

In [ ]:
exploded_df[exploded_df['ui'] == 'A36802459']

In [ ]:
exploded_df[exploded_df['rootSource'] == 'RXNORM']

In [ ]:
exploded_df[exploded_df['rootSource'] == 'MSH']

In [ ]:
# concatonate exploded_df and vac_df 
combined_df = pd.concat([exploded_df, vac_df], ignore_index=True)
# remove duplicates based on 'ui' column
combined_df = combined_df.drop_duplicates(subset='ui', keep='first')
combined_df['rootSource'].value_counts()

In [ ]:
# Unique number of conceptClean column
combined_df['conceptClean'].nunique()

In [ ]:
combined_df

In [45]:
athena_to_umls_map = {
    "MeSH": "MSH",                  # Medical Subject Headings
    "RxNorm Extension": "RXNORM_EXT",   # Usually merged into RXNORM in UMLS
    "RxNorm": "RXNORM",
    "GCN_SEQNO": "NDDF",             # Generic Code Number from First DataBank
    "SPL": "MTHSPL",                 # Structured Product Labeling
    "NDC": "NDC",                    # National Drug Code (if present in UMLS)
    "SNOMED": "SNOMEDCT_US",
    "CVX": "CVX",
    "CPT4": "CPT",                   
    "VANDF": "VANDF",
    "ATC": "ATC",
    "EphMRA ATC": "ATC",             # Map to ATC
    "HCPCS": "HCPCS",                
    "SNOMED Veterinary": "SNOMEDCT_VET", 
    "NDFRT": "VANDF",               
    "NCCD": "NCCD",                  
    "OMOP Invest Drug": "OMOPID",    
    "ICD10PCS": "ICD10PCS",          
    "GGR": "GGR",                    
    "KDC": "KDC",                    # Same
    "AMT": "AMT",                    # Australian Medicines Terminology
    "Nebraska Lexicon": "NEB_LEX", # No mapping in UMLS list
    "CO-CONNECT": "CO-CONNECT",      # Same
    "VA Class": "VANDF",             
    "dm+d": "DM+D",                  # UK dictionary of medicines + devices
    "HemOnc": "HemOnc",              # No UMLS equivalent
    "JMDC": "JMDC",                  # Same
    "BDPM": "BDPM",
    "CTD": "CTD",
    "EDI": "EDI",
    "DPD": "DPD",
    "Multum": "MMSL",                # Multum MedIndex = MMSL in UMLS
    "Read": "RCD",                   # Read Codes
    "CIEL": "CIEL"                   # Columbia International eHealth Lab
}

In [46]:
# read csv into dataframe
athena_df = pd.read_csv('results/Athena search[vaccine_valid_drug].csv', sep='\t')
athena_df.head()

,Id,Code,Name,Standard Class,Domain,Vocab,Validity,Concept
0,28493,D000068756,Valsartan,Main Heading,Drug,MeSH,Valid,Non-standard
1,28686,C576297,ponceau 4R,Suppl Concept,Drug,MeSH,Valid,Non-standard
2,32766,OMOP4873977,Middle East Respiratory Syndrome heterologous ...,Ingredient,Drug,RxNorm Extension,Valid,Standard
3,509104,347699,meningococcal group A polysaccharide 0.1 MG/ML...,Clinical Drug,Drug,RxNorm,Valid,Standard
4,514012,314724,meningococcal polysaccharide vaccine group W-135,Ingredient,Drug,RxNorm,Valid,Standard

In [65]:
athena_df['Vocab'].value_counts()

Vocab
RxNorm Extension     9156
RxNorm               2020
SPL                  1759
NDC                   862
dm+d                  840
AMT                   672
CPT4                  468
NDFRT                 333
SNOMED Veterinary     311
GCN_SEQNO             280
Nebraska Lexicon      255
SNOMED                250
MeSH                  202
CVX                   198
VANDF                 162
OMOP Invest Drug      153
BDPM                   88
DPD                    81
CIEL                   70
JMDC                   57
ATC                    52
Multum                 45
NCCD                   23
HCPCS                  21
EphMRA ATC             18
KDC                    13
CTD                    13
ICD10PCS               12
Read                   11
CO-CONNECT              8
HemOnc                  4
VA Class                3
GGR                     1
EDI                     1
Name: count, dtype: int64

In [47]:
athena_df['Vocab_UMLS'] = athena_df['Vocab'].map(athena_to_umls_map)

In [66]:
concatonated_df['rootSource'].value_counts()

rootSource
NCI              1531
MEDCIN            684
SNOMEDCT_US       532
RCD               348
RXNORM            304
MSH               294
NDDF              223
VANDF             152
ATC               135
CHV                81
CSP                73
SNMI               71
CVX                56
MTH                54
MMX                48
MMSL               47
GS                 39
USPMG              35
MEDLINEPLUS        33
MED-RT             32
MDR                32
LNC                25
MTHSPL             24
AOD                21
ICPC2ICD10ENG      20
SNM                19
ICPC2P             17
PDQ                14
LCH_NW             14
LCH                11
PSY                 9
ICD10CM             8
CST                 7
DXP                 7
HL7V3.0             6
COSTAR              6
CCS                 6
ICD10               5
BI                  5
NANDA-I             5
ICD10AM             5
CCPSS               4
OMIM                4
CCSR_ICD10CM        3
MTHICD9             3
RCDAE               3
ICD9CM              2
ICPC                2
ICPC2EENG           2
WHO                 2
ICNP                2
QMR                 1
ORPHANET            1
GO                  1
CDT                 1
CCSR_ICD10PCS       1
HL7V2.5             1
CPM                 1
Name: count, dtype: int64

In [48]:
# show the valuecounts of the 'Vocab' column (athena_df) and 'rootSource' column (combined_df) side by side
vocab_counts = athena_df['Vocab_UMLS'].value_counts()
# root_source_counts = combined_df['rootSource'].value_counts()
root_source_counts = concatonated_df['rootSource'].value_counts()
comparison_df = pd.DataFrame({'Athena': vocab_counts,
'UMLS': root_source_counts}).fillna(0).astype(int)
comparison_df

              Athena  UMLS
AMT              672     0
AOD                0    21
ATC               70   135
BDPM              88     0
BI                 0     5
...              ...   ...
SNOMEDCT_US      250   532
SNOMEDCT_VET     311     0
USPMG              0    35
VANDF            498   152
WHO                0     2

[79 rows x 2 columns]

In [ ]:
comparison_df

### ToDo: 
1. Add function to get related concepts (https://documentation.uts.nlm.nih.gov/rest/relations/)
2. Normalize vocab sources acros Athena and UMLS
3. Check vocabulary code to identify missing concepts from each source